[package]
name = "grd-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.99"
env_logger = "0.10"
fehler = "1"
futures = "0.3"
itertools = "0.11"
log = "0.4"
once_cell = "1"
rand = "0.8"
reqwest = { version = "0.11", features = ["gzip", "brotli", "json", "rustls-tls-native-roots"], default-features = false }
rkyv = "0.7"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shrinkwraprs = "0.3"
smart-default = "0.7"
sugars = "3"
tap = "1"
num-traits = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
