[package]
name = "grd-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-timer = "1.0.0-beta.8"
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.99"
env_logger = "0.10"
fehler = "1"
futures = "0.3"
hobo = { version = "0.4", optional = true }
itertools = "0.11"
js-sys = { version = "0.3", optional = true }
log = "0.4"
once_cell = "1"
rand = "0.8"
reqwest = { version = "0.11", features = ["gzip", "brotli", "json", "rustls-tls-native-roots"], default-features = false }
rkyv = "0.7"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shrinkwraprs = "0.3"
smart-default = "0.7"
sugars = "3"
tap = "1"
thiserror = "1"
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
wasm-logger = { version = "0.2", optional = true }
serde-wasm-bindgen = { version = "0.5", optional = true }
num-traits = "0.2"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# getrandom = { version = "*", features = ["js"] } # because of rand

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }

[features]
hobo_plus = ["js-sys", "wasm-bindgen", "wasm-bindgen-futures", "serde-wasm-bindgen", "wasm-logger", "hobo", "web-sys"]

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
	"IntersectionObserver",
	"IntersectionObserverInit",
	"IntersectionObserverEntry",
	"Url", "MediaSource","Blob",
]
