[package]
name = "grd-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
hobo = "0.1"
log = "0.4"
once_cell = "1"
reqwest = { version = "0.11", features = ["gzip", "brotli", "json", "rustls-tls", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smart-default = "0.6"
rand = "0.8"

wasm-bindgen = { version = "0.2", features = ["nightly"] }
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"

[patch.crates-io]
hobo = { path = "hobo/lib" }
hobo_derive = { path = "hobo/derive" }
hobo_css = { path = "hobo/css" }
hobo_css_macros = { path = "hobo/css/macros" }
